accountapp/urls.py
from django.urls import path
from . import views
from accountapp.views import SignupView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

freeapp/urls.py
app_name = 'freeapp'

urlpatterns = [

]

profileapp/urls.py
from django.urls import path
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

accountapp/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.core.mail import EmailMessage
from django.core.mail.message import EmailMessage
from accountapp.decorators import account_ownership_required
from accountapp.forms import UserForm, AccountUpdateForm
from accountapp.tokens import account_activation_token

has_ownership = [account_ownership_required, login_required]

class SignupView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/signup.html'

def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] ==request.POST['password2']:
            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
            user.is_active = False #유저 비활성화
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('accountapp/activation_email.html',
                                       {'user': user, 'domain': current_site.domain,
                                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                        'token': account_activation_token.make_token(user),})
            mail_title = "회원가입 확인 이메일"
            mail_to = request.POST["email"]
            email = EmailMessage(mail_title, message, to=[mail_to])
            email.send()
            return render(request, 'accountapp/login.html')
    # 포스트 방식 아니면 페이지 띄우기
    return render(request, 'accountapp/signup.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        # 로그인
        user = auth.authenticate(request, username=username, password=password)
        if user is not None: #성공
            auth.login(request, user)
            return redirect('home')
        else: #실패
            return render(request, 'accountapp/login.html', {'error':'아이디 또는 비밀번호를 다시 입력해주세요.'})
    else:
        return render(request, 'accountapp/login.html')

def logout(request):
    #if request.method == 'POST':
        auth.logout(request) #유저 로그아웃
        return redirect('home')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExsit):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        auth.login(request, user)
        return redirect("home")
    else:
        return render(request, 'home.html', {'error':'계정 활성화 오류'})


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'
    pagination_by = 8
    #def get_context_data(self, **kwargs):
     #   object_list = Article.objects.filter(writer=self.get_object())
      #  return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:detail')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/activation_email.html
{{user.username}}님, 아래 링크를 클릭하여 계정을 활성화하세요:
http://{{domain}}{% url 'accountapp:activate' uid token %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <br>
    <div>
        <p style="text-align:center;">
            회원 탈퇴 시, 탈퇴한 아이디로 다시 가입할 수 없으며<br>
            데이터 복구도 불가하오니 신중히 진행해주시길 바랍니다.
        </p>
    </div>
    <br>
    <div class="content_font sort_center" style="width: 400px; margin: 0 auto; ">
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary activate col-3">회원탈퇴</button>
        </form>
    </div>
    <br>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center; max-width: fit-content; margin: auto;">

    {% if target_user.profile %}
        <img src="{{ target_user.profile.image.url }}" alt="" style="width: 20rem; border-radius: 5rem; margin: 1rem;">
        <h6>{{ target_user.profile.nickname }}</h6>
        <div style="font-size: 12px;">
            {{ target_user.profile.message }}
            {% if target_user == user %}
                <a class="material-icons" style="color:lightslategrey;"
                    href="{% url 'profileapp:update' pk=target_user.profile.pk %}">edit</a>
            {% endif %}
        </div>
    {% else %}
        {% if target_user == user %}
            <a href="{% url 'profileapp:create' %}">Create...!</a>
        {% else %}
            <h10 style="margin: auto;">No Profile!</h10>
        {% endif %}
    {% endif %}

    <br><br><br><br>

    <br><br>

    <div style="font-size: 0.7rem;">
        {% if target_user == user %}
        <span>
            <a href="{% url 'accountapp:update' pk=user.pk %}" style="border: 1px solid darkgrey; border-radius: 30%;">Edit Info</a>
        </span>
        　
        <span>
            <a href="{% url 'accountapp:delete' pk=user.pk %}" style="border: 1px solid darkgrey; border-radius: 30%;">Withdrawal</a>
        </span>
        {% endif %}
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="max-width: 300px; margin: 4rem auto">
        <div style="text-align: center;"><h4><b>로그인</b></h4></div>
        <br>
        <div>
            <form action="{% url 'accountapp:login' %}" method="POST">
                {% csrf_token %}
                <span>아이디 :   <input name="username" type="text"></span>
                <br><br>
                <span>비밀번호 :   <input name="password" type="password"></span>

                <br><br>
                <div style="text-align: center;">
                    <input type="submit" class="btn btn-secondary btn-sm" value="로그인" style="margin-bottom:1rem;">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="width: 300px; margin: 0 auto;">
      <h4 style="text-align: center">회원가입</h4>
      <br>
      <form method="post" action="" style="font-size:1.3rem;">
          {% csrf_token %}
          <div>아이디 <input name="username" type="text" value=""></div>
          <br>
          <div>이메일 <input name="email" type="email" value=""></div>
          <br>
          <div>비밀번호 <input name="password1" type="password" value=""></div>
          <br>
          <div>비밀번호 확인 <input name="password2" type="password" value=""></div>
          <br>
          <div style="text-align:center">
            <input class="btn btn-secondary btn-sm" type="submit" value="회원가입">
          </div>
      </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="content_font" style="width: 400px; margin: 0 auto;">
      <div>
        <h4>Change Info</h4>
      </div>
      <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-secondary activate col-3">
      </form>
    </div>

{% endblock %}