accountapp/urls.py
from django.urls import path
from . import views
from accountapp.views import SignupView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

dongariapp/urls.py
from django.urls import path
from . import views

app_name = 'dongariapp'

urlpatterns = [
    path('list/', views.PostList.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetail.as_view()),
    #path('<int:pk>/', views.single_post_page),
    #path('', views.index),
]

freeapp/urls.py
app_name = 'freeapp'

urlpatterns = [

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

    {% include 'head.html' %}

    <body style="font-family: 'NanumSquare_0';">
        {% include 'header.html' %}

        <br>
        {% block content %}
        <br><br>

        {% endblock %}

        <br><br><hr><br>
        {% include 'footer.html' %}
        <br><br><br>
    </body>
</html>

templates/footer.html
<div style="text-align:center;">
    <div style="font-size: .8rem;">
        <span>김민성</span>
        <span>조윤주</span>
        <span>도욱현</span>
    </div>
    <br><br>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>마피아 해커톤</title>

    <!--   BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <!--  GOOGLE FONTS LINK  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Festive&display=swap" rel="stylesheet">

    <!--  GOOGLE MATERIAL ICONS  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!--  DEFAULT CSS LINK  -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquare_0';
            src: local('NanumSquare_0'),
            url("{% static 'fonts/NanumSquare_0.ttf' %}") format("opentype");
        }
    </style>


</head>

templates/header.html
<style>a{text-decoration: none; color: black;}</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">⬛</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dongariapp:post_list' %}">동아리</a>
                    </li>
                   {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accountapp:login' %}?next={{ request.path }}">로그인</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accountapp:signup' %}">회원가입</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accountapp:detail' pk=user.pk %}">마이페이지</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accountapp:logout' %}?next={{ request.path }}">로그아웃</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
</nav>